### ISSUE TITLE
Version number too strict

### ISSUE THREAD

**Issue by NatoBoram** [RinF-UwU/AutoclickerRnF#2]
![image](https://github.com/RinF-UwU/AutoclickerRnF/assets/10495562/7567b807-2a61-4f4e-9b6b-15ec0d4707b3)

**Comment by RinF-UwU** [comment]
Thanks for the reminder, I have updated the mod to versions 1.19.4 and 1.20. The latter can be downloaded here on GitHub, and 1.19.4 will be available on CurseForge soon.
